# Generated by Django 5.1.6 on 2025-02-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('drugbank_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('chronic_conditions', models.TextField(help_text='List of chronic diseases')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('alternatives', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('drug_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacting_drug_1', to='interactions.medication')),
                ('drug_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacting_drug_2', to='interactions.medication')),
            ],
            options={
                'unique_together': {('drug_1', 'drug_2')},
            },
        ),
    ]
