# Generated by Django 5.1.6 on 2025-02-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginteraction',
            old_name='description',
            new_name='interaction',
        ),
        migrations.RemoveField(
            model_name='druginteraction',
            name='alternatives',
        ),
        migrations.RemoveField(
            model_name='druginteraction',
            name='checked_at',
        ),
        migrations.RemoveField(
            model_name='druginteraction',
            name='risk_level',
        ),
        migrations.AlterField(
            model_name='druginteraction',
            name='drug_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='druginteraction',
            name='drug_2',
            field=models.CharField(max_length=255),
        ),
    ]
