# Generated by Django 5.1.6 on 2025-02-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_druginteraction_source_alter_druginteraction_drug_1_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='druginteraction',
            name='interaction_drug_1_69375c_idx',
        ),
    ]
