# Generated by Django 5.1.6 on 2025-03-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_remove_patientmedication_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedinteraction',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientlist',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
