# Generated by Django 5.1.6 on 2025-03-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_remove_savedinteraction_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(unique=True)),
                ('new_medications', models.TextField()),
                ('current_medications', models.TextField()),
            ],
        ),
    ]
