# Generated by Django 5.1.6 on 2026-08-12 14:53

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_temporaryprescription_patient_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_1', models.CharField(max_length=255)),
                ('drug_2', models.CharField(max_length=255)),
                ('interaction', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='gemini', max_length=50)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'interaction lookup cache',
            },
        ),
        migrations.AddField(
            model_name='savedinteraction',
            name='checked_by',
            field=models.ForeignKey(blank=True, help_text='Doctor who ran the check. Kept if the account is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(django.db.models.functions.text.Lower('drug_1'), django.db.models.functions.text.Lower('drug_2'), name='drug_pair_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='patientlist',
            index=models.Index(fields=['-registered_date'], name='patient_registered_idx'),
        ),
        migrations.AddIndex(
            model_name='patientlist',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='patient_name_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='savedinteraction',
            index=models.Index(fields=['patient', '-checked_at'], name='saved_patient_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interactionlookupcache',
            unique_together={('drug_1', 'drug_2')},
        ),
    ]
