# Generated by Django 5.2.17 on 2026-08-12 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_interactionlookupcache_savedinteraction_checked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('frequency', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='patientlist',
            name='patient_registered_idx',
        ),
        migrations.AddField(
            model_name='patientlist',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Owning doctor. NULL marks a legacy row created before patients were scoped; those are visible to nobody through the API. Use `manage.py assign_patients` to adopt them.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AddIndex(
            model_name='patientlist',
            index=models.Index(fields=['doctor', '-registered_date'], name='patient_doctor_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientlist',
            constraint=models.UniqueConstraint(fields=('doctor', 'phone_number'), name='unique_patient_phone_per_doctor'),
        ),
        migrations.AddConstraint(
            model_name='patientlist',
            constraint=models.UniqueConstraint(fields=('doctor', 'email'), name='unique_patient_email_per_doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='interactions.patientlist'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, help_text="Kept as a record if the doctor's account is later deleted.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedinteraction',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Prescription that triggered this warning. NULL for standalone checks that were run without issuing a prescription.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='interactions.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interactions.prescription'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-created_at'], name='rx_patient_time_idx'),
        ),
    ]
