# Generated by Django 5.2.17 on 2026-08-12 17:27

from django.db import migrations, models


def rename_gemini_source(apps, schema_editor):
    """Migrate the old free-text source value onto the new choice set.

    Cached rows written before this migration used source='gemini'. The field is
    now a choice field whose AI value is 'ai_unverified'; without this, those
    rows would keep a value that is no longer in `choices` and would render with
    a blank label in the UI and admin.
    """
    apps.get_model("interactions", "InteractionLookupCache").objects.filter(
        source="gemini"
    ).update(source="ai_unverified")


def restore_gemini_source(apps, schema_editor):
    apps.get_model("interactions", "InteractionLookupCache").objects.filter(
        source="ai_unverified"
    ).update(source="gemini")


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_prescription_prescriptionitem_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_gemini_source, restore_gemini_source),
        migrations.CreateModel(
            name='DrugNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queried_name', models.CharField(help_text='Normalized form of what was typed.', max_length=255, unique=True)),
                ('ingredient', models.CharField(blank=True, default='', help_text='Resolved ingredient name; empty means RxNorm had no match.', max_length=255)),
                ('rxcui', models.CharField(blank=True, default='', max_length=32)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'drug name aliases',
            },
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='management_recommendation',
            field=models.TextField(blank=True, default='', help_text='What the prescriber should do about it, when the source says.'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='severity',
            field=models.CharField(choices=[('contraindicated', 'Contraindicated'), ('major', 'Major'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='interactionlookupcache',
            name='severity',
            field=models.CharField(choices=[('contraindicated', 'Contraindicated'), ('major', 'Major'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='savedinteraction',
            name='management_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='savedinteraction',
            name='severity',
            field=models.CharField(choices=[('contraindicated', 'Contraindicated'), ('major', 'Major'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='savedinteraction',
            name='source',
            field=models.CharField(choices=[('dataset', 'Curated dataset'), ('openfda', 'openFDA drug label'), ('ai_unverified', 'AI-generated (unverified)')], default='dataset', max_length=20),
        ),
        migrations.AlterField(
            model_name='interactionlookupcache',
            name='source',
            field=models.CharField(choices=[('dataset', 'Curated dataset'), ('openfda', 'openFDA drug label'), ('ai_unverified', 'AI-generated (unverified)')], default='ai_unverified', max_length=20),
        ),
    ]
