# Generated by Django 5.2.17 on 2026-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_drugnamealias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='unscreened_pair_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
